language: php

matrix:
  include:
    - php: 5.3
      dist: precise
  allow_failures:
    - php: hhvm

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer install --dev

script:
  - vendor/bin/phpunit --colors=always --bootstrap ./tests/bootstrap.php ./tests --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
